gText_Birch_Welcome::
	.string "Welcome to the world of Pokémon!\p"
	.string "I am Augustine Sycamore, the Kalos\n"
	.string "region's very own Pokémon Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This world of ours is widely inhabited by creatures\n"
	.string "known as Pokémon!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "These mysterious creatures can be found\n"
	.string "in every corner of our world…\p"
	.string "Some run across the plains, others fly\n"
	.string "through the skies, and others yet swim\l"
	.string "deep in the oceans…\p"
	.string "We live together with these Pokémon,\n"
	.string "lending our strength to one another to\l"
	.string "live and prosper.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's get started!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Oho, I see.\n"
	.string "Would you tell me your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}, then?\n"
	.string "Did I get that right?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}… Tres bien!\n"
	.string "What a fantastic name!\p"
	.string "{PLAYER}{KUN}, your adventure begins now!\l"
	.string "You are about to enter the beautiful\n"
	.string "Kalos region!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Go and meet many Pokemon and people, and\n"
	.string "fill your life with rich experiences!\p"
	.string "Now let's go visit the world of Pokemon!\p"
	.string "$"